// Seed mock data for first launch — feels lived-in.
import type {
  AppNotification,
  Friend,
  Gig,
  LocalArtist,
  Rankings,
  UpcomingShow,
  User,
  Venue,
} from '../types';
import { isoDaysAgo, isoDaysFromNow, ticketDate, ago } from '../lib/dates';

export const seedUser: User = {
  name: 'alex chen',
  handle: 'alex',
  bio: 'seen 47 · 6 sold-out · 1 cancelled (rip)',
  city: 'NYC',
  avaColor: 'olive',
};

export const seedFriends: Friend[] = [
  { handle: 'raquel', name: 'raquel',  avaColor: 'terracotta', following: true,  city: 'CDMX',  bio: 'metal + emo, will travel' },
  { handle: 'mateo',  name: 'mateo',   avaColor: 'olive',      following: true,  city: 'LA',    bio: 'kpop, indie, anything loud' },
  { handle: 'ines',   name: 'ines',    avaColor: 'plum',       following: true,  city: 'BCN',   bio: 'singer-songwriter, sad girl szn' },
  { handle: 'jules',  name: 'jules',   avaColor: 'mustard',    following: false, city: 'NYC',   bio: 'shoegaze + post-punk' },
  { handle: 'kai',    name: 'kai',     avaColor: 'indigo',     following: false, city: 'LDN',   bio: 'dnb, jungle, the warehouse' },
  { handle: 'sam',    name: 'sam',     avaColor: 'terracotta', following: false, city: 'NYC',   bio: 'folk, americana, basement shows' },
];

export const seedVenues: Venue[] = [
  { id: 1, name: 'Brooklyn Steel',       slug: 'brooklyn-steel',       city: 'NYC',  status: 'visited',  x: 38, y: 38 },
  { id: 2, name: 'Bowery Ballroom',      slug: 'bowery-ballroom',      city: 'NYC',  status: 'visited',  x: 30, y: 50 },
  { id: 3, name: 'Madison Square Gdn',   slug: 'madison-square-gdn',   city: 'NYC',  status: 'visited',  x: 48, y: 30 },
  { id: 4, name: 'Forest Hills Stadium', slug: 'forest-hills-stadium', city: 'NYC',  status: 'visited',  x: 64, y: 44 },
  { id: 5, name: 'Webster Hall',         slug: 'webster-hall',         city: 'NYC',  status: 'visited',  x: 42, y: 58 },
  { id: 6, name: 'Radio City',           slug: 'radio-city',           city: 'NYC',  status: 'upcoming', x: 56, y: 22 },
  { id: 7, name: 'Knockdown Center',     slug: 'knockdown-center',     city: 'NYC',  status: 'wishlist', x: 70, y: 60 },
  { id: 8, name: 'Foro Sol',             slug: 'foro-sol',             city: 'CDMX', status: 'visited',  x: 22, y: 78 },
  { id: 9, name: 'Kia Forum',            slug: 'kia-forum',            city: 'LA',   status: 'visited',  x: 12, y: 42 },
  { id: 10, name: 'Palau Sant Jordi',    slug: 'palau-sant-jordi',     city: 'BCN',  status: 'visited',  x: 84, y: 30 },
];

const photoMet = '/assets/inspiration/journal-metallica.jpeg';
const photoXG  = '/assets/inspiration/journal-xg.jpeg';
const photoMus = '/assets/inspiration/journal-museu.jpeg';

export const seedGigs: Gig[] = [
  {
    id: 1,
    user: 'raquel',
    artist: 'Metallica',
    artistSlug: 'metallica',
    tour: 'M72 Tour',
    venue: 'Foro Sol',
    venueSlug: 'foro-sol',
    city: 'CDMX',
    dateISO: isoDaysAgo(0, 22),
    date: ticketDate(isoDaysAgo(0, 22)),
    tier: 'loved',
    note: '2nd time',
    review: "Pyro on Master of Puppets was unreal. Sound was rough at first — sorted by Sad But True. Worth the trip.",
    tags: ['SOLD OUT', 'WITH FRIENDS'],
    photo: photoMet,
    scope: 'friend',
    likes: 12,
    comments: [
      { id: 1, user: 'mateo', body: 'jealous. that pyro changed me when I saw them in 22.', ago: '2h ago' },
      { id: 2, user: 'alex',  body: 'next time we both go.', ago: '1h ago' },
    ],
    liked: false,
  },
  {
    id: 2,
    user: 'mateo',
    artist: 'XG',
    artistSlug: 'xg',
    tour: 'The 1st Howl',
    venue: 'Kia Forum',
    venueSlug: 'kia-forum',
    city: 'LA',
    dateISO: isoDaysAgo(2, 21),
    date: ticketDate(isoDaysAgo(2, 21)),
    tier: 'loved',
    review: "Choreography was insane. Setlist was tight, ended on Left Right. Drinks $19 lol.",
    tags: ['FRONT ROW'],
    photo: photoXG,
    scope: 'friend',
    likes: 28,
    comments: [],
    liked: true,
  },
  {
    id: 3,
    user: 'ines',
    artist: 'Phoebe Bridgers',
    artistSlug: 'phoebe-bridgers',
    venue: 'Palau Sant Jordi',
    venueSlug: 'palau-sant-jordi',
    city: 'BCN',
    dateISO: isoDaysAgo(5, 21),
    date: ticketDate(isoDaysAgo(5, 21)),
    tier: 'mid',
    note: 'first time',
    review: 'Cried twice. The strings on Moon Song. Need to go again.',
    tags: ['CRIED', 'FIRST TIME'],
    photo: photoMus,
    scope: 'friend',
    likes: 41,
    comments: [],
    liked: false,
  },
  // Self gigs
  {
    id: 4,
    user: 'alex',
    artist: 'Metallica',
    artistSlug: 'metallica',
    tour: 'M72 Tour',
    venue: 'Madison Square Gdn',
    venueSlug: 'madison-square-gdn',
    city: 'NYC',
    dateISO: isoDaysAgo(60, 21),
    date: ticketDate(isoDaysAgo(60, 21)),
    tier: 'loved',
    review: 'best night of my year. Bell Tolls into Whiplash, no breath.',
    tags: ['FRONT ROW', 'WITH FRIENDS', 'ENCORE'],
    photo: photoMet,
    scope: 'self',
    likes: 9,
    comments: [],
    liked: false,
  },
  {
    id: 5,
    user: 'alex',
    artist: 'XG',
    artistSlug: 'xg',
    tour: '1st Howl',
    venue: 'Webster Hall',
    venueSlug: 'webster-hall',
    city: 'NYC',
    dateISO: isoDaysAgo(28, 22),
    date: ticketDate(isoDaysAgo(28, 22)),
    tier: 'loved',
    review: 'Choreo + vocals + crowd. Left at 5am drenched.',
    tags: ['SOLD OUT'],
    photo: photoXG,
    scope: 'self',
    likes: 14,
    comments: [],
    liked: false,
  },
  {
    id: 6,
    user: 'alex',
    artist: 'Phoebe Bridgers',
    artistSlug: 'phoebe-bridgers',
    venue: 'Forest Hills Stadium',
    venueSlug: 'forest-hills-stadium',
    city: 'NYC',
    dateISO: isoDaysAgo(120, 20),
    date: ticketDate(isoDaysAgo(120, 20)),
    tier: 'loved',
    review: 'rain made it. Moon Song with thunder rolling in.',
    tags: ['CRIED', 'RAINY'],
    photo: photoMus,
    scope: 'self',
    likes: 22,
    comments: [],
    liked: false,
  },
  {
    id: 7,
    user: 'alex',
    artist: 'beabadoobee',
    artistSlug: 'beabadoobee',
    venue: 'Brooklyn Steel',
    venueSlug: 'brooklyn-steel',
    city: 'NYC',
    dateISO: isoDaysAgo(11, 21),
    date: ticketDate(isoDaysAgo(11, 21)),
    tier: 'mid',
    review: 'lower energy than I wanted but the closer was perfect.',
    tags: [],
    photo: photoMus,
    scope: 'self',
    likes: 5,
    comments: [],
    liked: false,
  },
  {
    id: 8,
    user: 'alex',
    artist: 'Fontaines D.C.',
    artistSlug: 'fontaines-dc',
    venue: 'Bowery Ballroom',
    venueSlug: 'bowery-ballroom',
    city: 'NYC',
    dateISO: isoDaysAgo(36, 22),
    date: ticketDate(isoDaysAgo(36, 22)),
    tier: 'loved',
    review: 'Starburster nearly broke the floor.',
    tags: ['PIT'],
    photo: photoXG,
    scope: 'self',
    likes: 11,
    comments: [],
    liked: false,
  },
  {
    id: 9,
    user: 'alex',
    artist: 'Clairo',
    artistSlug: 'clairo',
    venue: 'Brooklyn Steel',
    venueSlug: 'brooklyn-steel',
    city: 'NYC',
    dateISO: isoDaysAgo(50, 20),
    date: ticketDate(isoDaysAgo(50, 20)),
    tier: 'mid',
    review: 'gentle, slow, lovely. Sound mix was off until 4 songs in.',
    tags: [],
    photo: photoMet,
    scope: 'self',
    likes: 4,
    comments: [],
    liked: false,
  },
  {
    id: 10,
    user: 'alex',
    artist: 'IDLES',
    artistSlug: 'idles',
    venue: 'Brooklyn Steel',
    venueSlug: 'brooklyn-steel',
    city: 'NYC',
    dateISO: isoDaysAgo(72, 22),
    date: ticketDate(isoDaysAgo(72, 22)),
    tier: 'loved',
    review: 'CONGRATULATIONS, no notes.',
    tags: ['PIT'],
    photo: photoMus,
    scope: 'self',
    likes: 19,
    comments: [],
    liked: false,
  },
];

// Strangers — people you don't follow. Their logs power the "Artists" tab.
export const seedStrangerGigs: Gig[] = [
  {
    id: 101, user: 'jamie', artist: 'Metallica', artistSlug: 'metallica', tour: 'M72 Tour',
    venue: 'MetLife Stadium', venueSlug: 'metlife-stadium', city: 'NYC',
    dateISO: isoDaysAgo(8, 21), date: ticketDate(isoDaysAgo(8, 21)),
    tier: 'loved',
    review: 'Hetfield was on fire. Pyro for Master made my chest shake. Side-stage seats, perfect view.',
    tags: ['FRONT ROW'], photo: photoMet, scope: 'stranger', likes: 87, comments: [], liked: false,
  },
  {
    id: 102, user: 'taylor', artist: 'Metallica', artistSlug: 'metallica', tour: 'M72 Tour',
    venue: 'Madison Square Gdn', venueSlug: 'madison-square-gdn', city: 'NYC',
    dateISO: isoDaysAgo(15, 22), date: ticketDate(isoDaysAgo(15, 22)),
    tier: 'mid',
    review: 'Sound mix in the lower bowl was muddy until 4 songs in. Setlist was strong but I wanted more thrash.',
    tags: [], photo: photoMet, scope: 'stranger', likes: 24, comments: [], liked: false,
  },
  {
    id: 103, user: 'drew', artist: 'XG', artistSlug: 'xg', tour: '1st Howl',
    venue: 'The Wiltern', venueSlug: 'the-wiltern', city: 'LA',
    dateISO: isoDaysAgo(4, 21), date: ticketDate(isoDaysAgo(4, 21)),
    tier: 'loved',
    review: 'Tippy mic moment was surreal. Crowd knew every word, every chant. Best night of the month.',
    tags: ['SOLD OUT', 'WITH FRIENDS'], photo: photoXG, scope: 'stranger', likes: 156, comments: [], liked: false,
  },
  {
    id: 104, user: 'casey', artist: 'XG', artistSlug: 'xg',
    venue: 'Kia Forum', venueSlug: 'kia-forum', city: 'LA',
    dateISO: isoDaysAgo(2, 22), date: ticketDate(isoDaysAgo(2, 22)),
    tier: 'loved',
    review: "Chisa hit a note in WOKE UP that I've been thinking about for two days.",
    tags: [], photo: photoXG, scope: 'stranger', likes: 64, comments: [], liked: false,
  },
  {
    id: 105, user: 'leo', artist: 'Phoebe Bridgers', artistSlug: 'phoebe-bridgers',
    venue: 'Greek Theatre', venueSlug: 'greek-theatre', city: 'LA',
    dateISO: isoDaysAgo(7, 21), date: ticketDate(isoDaysAgo(7, 21)),
    tier: 'loved',
    review: "Punisher under the open sky. cried, laughed, cried again. Phoebe's banter killed me.",
    tags: ['CRIED', 'FIRST TIME'], photo: photoMus, scope: 'stranger', likes: 203, comments: [], liked: false,
  },
  {
    id: 106, user: 'riv', artist: 'Phoebe Bridgers', artistSlug: 'phoebe-bridgers',
    venue: 'Webster Hall', venueSlug: 'webster-hall', city: 'NYC',
    dateISO: isoDaysAgo(14, 21), date: ticketDate(isoDaysAgo(14, 21)),
    tier: 'mid',
    review: 'I love her. The room was too hot. The encore saved it.',
    tags: ['SOLD OUT'], photo: photoMus, scope: 'stranger', likes: 41, comments: [], liked: false,
  },
  {
    id: 107, user: 'noor', artist: 'Fontaines D.C.', artistSlug: 'fontaines-dc',
    venue: 'Terminal 5', venueSlug: 'terminal-5', city: 'NYC',
    dateISO: isoDaysAgo(20, 22), date: ticketDate(isoDaysAgo(20, 22)),
    tier: 'loved',
    review: 'Chatten was unreal. Started in the back, ended in the pit. Skinty Fia closer turned the place into a rave.',
    tags: ['PIT'], photo: photoXG, scope: 'stranger', likes: 119, comments: [], liked: false,
  },
  // Local-artist gigs in NYC — these get a LOCAL badge in the Local feed
  {
    id: 108, user: 'simi', artist: 'Wednesday Pain', artistSlug: 'wednesday-pain',
    venue: 'Trans-Pecos', venueSlug: 'trans-pecos', city: 'NYC',
    dateISO: isoDaysAgo(3, 22), date: ticketDate(isoDaysAgo(3, 22)),
    tier: 'loved',
    review: "shoegaze in a basement, the way it should be. didn't expect to know every song.",
    tags: [], photo: photoMus, scope: 'stranger', likes: 32, comments: [], liked: false,
  },
  {
    id: 109, user: 'theo', artist: 'Tan & Sober Gentlemen', artistSlug: 'tan-sober-gentlemen',
    venue: 'Mercury Lounge', venueSlug: 'mercury-lounge', city: 'NYC',
    dateISO: isoDaysAgo(6, 21), date: ticketDate(isoDaysAgo(6, 21)),
    tier: 'loved',
    review: 'folk that hits in the chest. the fiddle, the foot stomps, the guy in front of me crying.',
    tags: ['FIRST TIME'], photo: photoMet, scope: 'stranger', likes: 21, comments: [], liked: false,
  },
  {
    id: 110, user: 'maya', artist: 'Crumb', artistSlug: 'crumb',
    venue: 'Brooklyn Steel', venueSlug: 'brooklyn-steel', city: 'NYC',
    dateISO: isoDaysAgo(9, 22), date: ticketDate(isoDaysAgo(9, 22)),
    tier: 'loved',
    review: 'psych jams that built and built. their drummer was unreal.',
    tags: ['SOLD OUT'], photo: photoXG, scope: 'stranger', likes: 47, comments: [], liked: false,
  },
  {
    id: 111, user: 'aki', artist: 'Ducks Ltd.', artistSlug: 'ducks-ltd',
    venue: "Baby's All Right", venueSlug: 'babys-all-right', city: 'NYC',
    dateISO: isoDaysAgo(13, 21), date: ticketDate(isoDaysAgo(13, 21)),
    tier: 'loved',
    review: 'jangle pop, perfect Wednesday night. ended at 11, home by 12, glad I went.',
    tags: [], photo: photoMus, scope: 'stranger', likes: 14, comments: [], liked: false,
  },
  {
    id: 112, user: 'kira', artist: 'The Cool Greenhouse', artistSlug: 'cool-greenhouse',
    venue: 'Knockdown Center', venueSlug: 'knockdown-center', city: 'NYC',
    dateISO: isoDaysAgo(17, 22), date: ticketDate(isoDaysAgo(17, 22)),
    tier: 'mid',
    review: "tighter on record. live they were a bit shaky on the openers but locked in by track 5.",
    tags: [], photo: photoMet, scope: 'stranger', likes: 9, comments: [], liked: false,
  },
];

// Self gigs in user-preferred order, best first. Friend gigs aren't ranked here.
export const seedRankings: Rankings = {
  loved: [4, 5, 6, 8, 10],
  mid: [7, 9],
  nah: [],
};

export const seedFollowedArtists: string[] = ['metallica', 'xg', 'phoebe-bridgers'];

export const seedUpcoming: UpcomingShow[] = [
  {
    id: 1,
    artist: 'Mitski',
    artistSlug: 'mitski',
    venue: 'Radio City Music Hall',
    venueSlug: 'radio-city',
    city: 'NYC',
    dateISO: isoDaysFromNow(12, 20),
    date: 'Sat · 14 Dec',
    score: 9.1,
    sold: true,
    genre: 'Indie',
  },
  {
    id: 2,
    artist: 'Big Thief',
    artistSlug: 'big-thief',
    venue: 'Brooklyn Steel',
    venueSlug: 'brooklyn-steel',
    city: 'NYC',
    dateISO: isoDaysFromNow(17, 20),
    date: 'Thu · 19 Dec',
    score: 8.7,
    sold: false,
    genre: 'Indie',
  },
  {
    id: 3,
    artist: 'Geese',
    artistSlug: 'geese',
    venue: 'Bowery Ballroom',
    venueSlug: 'bowery-ballroom',
    city: 'NYC',
    dateISO: isoDaysFromNow(25, 20),
    date: 'Fri · 27 Dec',
    score: 7.8,
    sold: false,
    genre: 'Rock',
  },
  {
    id: 4,
    artist: 'Black Country, New Road',
    artistSlug: 'black-country-new-road',
    venue: 'Webster Hall',
    venueSlug: 'webster-hall',
    city: 'NYC',
    dateISO: isoDaysFromNow(40, 20),
    date: 'Sun · 11 Jan',
    score: 8.9,
    sold: false,
    genre: 'Rock',
  },
  {
    id: 5,
    artist: 'Wednesday',
    artistSlug: 'wednesday',
    venue: 'Knockdown Center',
    venueSlug: 'knockdown-center',
    city: 'NYC',
    dateISO: isoDaysFromNow(54, 20),
    date: 'Sun · 25 Jan',
    score: 8.2,
    sold: false,
    genre: 'Rock',
  },
  {
    id: 6,
    artist: 'Aphex Twin',
    artistSlug: 'aphex-twin',
    venue: 'Forest Hills Stadium',
    venueSlug: 'forest-hills-stadium',
    city: 'NYC',
    dateISO: isoDaysFromNow(85, 20),
    date: 'Sat · 25 Feb',
    score: 9.5,
    sold: true,
    genre: 'Electronic',
  },
];

export const seedLocalArtists: LocalArtist[] = [
  { artist: 'Tan & Sober Gentlemen', artistSlug: 'tan-sober-gentlemen', genre: 'folk',       score: 9.2, gigs: 14 },
  { artist: 'The Cool Greenhouse',   artistSlug: 'cool-greenhouse',     genre: 'post-punk',  score: 8.6, gigs: 9 },
  { artist: 'Wednesday Pain',        artistSlug: 'wednesday-pain',      genre: 'shoegaze',   score: 8.1, gigs: 6 },
  { artist: 'Ducks Ltd.',            artistSlug: 'ducks-ltd',           genre: 'jangle',     score: 7.9, gigs: 11 },
  { artist: 'Crumb',                 artistSlug: 'crumb',               genre: 'psych',      score: 8.4, gigs: 8 },
];

export const seedNotifications: AppNotification[] = [
  {
    id: 1,
    kind: 'like',
    actor: 'raquel',
    gigId: 4,
    body: 'liked your Metallica log',
    ago: ago(isoDaysAgo(0, 18)),
    read: false,
  },
  {
    id: 2,
    kind: 'comment',
    actor: 'mateo',
    gigId: 1,
    body: 'commented on raquel\'s gig',
    ago: ago(isoDaysAgo(0, 12)),
    read: false,
  },
  {
    id: 3,
    kind: 'follow',
    actor: 'jules',
    body: 'started following you',
    ago: ago(isoDaysAgo(1, 14)),
    read: true,
  },
  {
    id: 4,
    kind: 'upcoming',
    body: 'Mitski opens in 12 days · sold out',
    ago: ago(isoDaysAgo(2, 9)),
    read: true,
  },
  {
    id: 5,
    kind: 'like',
    actor: 'ines',
    gigId: 5,
    body: 'liked your XG log',
    ago: ago(isoDaysAgo(3, 10)),
    read: true,
  },
];
